spring:
  application:
    name: health-check
  datasource:
    url: jdbc:postgresql://localhost:15432/healthdb
    username: health
    password: healthpass
    hikari:
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: healthdb
    redis:
      host: localhost
      port: 16379
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

monitoring:
  mock-server-url: http://localhost:18080/health

health-check:
  critical-services:
    - name: postgres
      interval: 5000
    - name: redis
      interval: 5000
  non-critical-services:
    - name: rabbitmq
      interval: 10000
    - name: mongodb
      interval: 10000
    - name: mockWebServer
      interval: 15000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      status:
        http-mapping:
          DEGRADED: 200
      group:
        readiness:
          include:
            - degradedReadiness
          status:
            order: DOWN, DEGRADED, UP
  health:
    defaults:
      enabled: false
